[package]
name = "NuwaFramework"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/rooch-network/rooch", subdir = "frameworks/move-stdlib", rev = "d0a8b58e2c1688d67ba5e1424e591de90bf85162" }
MoveosStdlib = { git = "https://github.com/rooch-network/rooch", subdir = "frameworks/moveos-stdlib", rev = "d0a8b58e2c1688d67ba5e1424e591de90bf85162" }
RoochFramework = { git = "https://github.com/rooch-network/rooch", subdir = "frameworks/rooch-framework", rev = "d0a8b58e2c1688d67ba5e1424e591de90bf85162" }
BitcoinMove = { git = "https://github.com/rooch-network/rooch", subdir = "frameworks/bitcoin-move", rev = "d0a8b58e2c1688d67ba5e1424e591de90bf85162" }
VerityMoveOracles = { git = "https://github.com/usherlabs/verity-move-oracles", subdir = "rooch", rev = "6850988a66151749f713a2496942c09885167a82"}

[addresses]
nuwa_framework = "_"
verity = "0xf1290fb0e7e1de7e92e616209fb628970232e85c4c1a264858ff35092e1be231"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"

[dev-addresses]
nuwa_framework = "0x42"
