providers = ["node"]

[phases.setup]
nixPkgs = ['nodejs', 'pnpm']
cmds = ['cd nuwa-services/cadop-service/typescript']

[phases.install]
cmds = ['pnpm install']

[phases.build]
cmds = [
    'pnpm --filter @cadop/shared build',
    'pnpm --filter @cadop/api build'
]

[start]
cmd = 'cd packages/cadop-api && pnpm start:prod'
