packages:
  # nuwa-kit packages
  - 'nuwa-kit/typescript/packages/*'
  # nuwa-kit examples (excluding certain packages)
  - 'nuwa-kit/typescript/examples/*'
  # nuwa-services
  - 'nuwa-services/cadop-service'
  # cadop-service sub-packages (web/shared/api)
  - 'nuwa-services/cadop-service/packages/*'
  - 'nuwa-services/llm-gateway'
  - 'nuwa-services/mcp-server-proxy' 
  # Exclusions
  - '!nuwa-services/capstore-indexer/**'
  
