create table faucet_claims (
  id bigint generated by default as identity primary key,
  did text not null,
  address text not null,
  claimed_amount bigint not null,
  created_at timestamptz default now()
);
