[package]
name = "NuwaFramework"
version = "1.0.0"

[dependencies]
MoveStdlib = { git = "https://github.com/rooch-network/rooch", subdir = "frameworks/move-stdlib", rev = "a9a0cff6a1896ef587585dbd088073358b6b6444" }
MoveosStdlib = { git = "https://github.com/rooch-network/rooch", subdir = "frameworks/moveos-stdlib", rev = "a9a0cff6a1896ef587585dbd088073358b6b6444" }
RoochFramework = { git = "https://github.com/rooch-network/rooch", subdir = "frameworks/rooch-framework", rev = "a9a0cff6a1896ef587585dbd088073358b6b6444" }
BitcoinMove = { git = "https://github.com/rooch-network/rooch", subdir = "frameworks/bitcoin-move", rev = "a9a0cff6a1896ef587585dbd088073358b6b6444" }
VerityMoveOracles = { git = "https://github.com/usherlabs/verity-move-oracles", subdir = "rooch", rev = "6850988a66151749f713a2496942c09885167a82"}
gas_market = { git = "https://github.com/rooch-network/rooch", subdir = "apps/gas_market", rev = "a9a0cff6a1896ef587585dbd088073358b6b6444" }

[addresses]
nuwa_framework = "_"
verity = "0xf1290fb0e7e1de7e92e616209fb628970232e85c4c1a264858ff35092e1be231"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
bitcoin_move = "0x4"
gas_market = "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3"
app_admin = "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3"

[dev-addresses]
nuwa_framework = "0x42"
