# MCP Server Proxy Configuration

# HTTP Server Settings
server:
  host: "0.0.0.0"
  port: 8088
  cors:
    origin: "*"
    methods: ["GET", "POST", "OPTIONS"]
  logger:
    level: "info"
    prettyPrint: true

# Default upstream when no route matches
defaultUpstream: "amap"

# Upstream MCP servers
upstreams:

  context7:
    type: "stdio"
    command: ["npx", "-y", "@upstash/context7-mcp@latest"]
  amap:
    type: "http"
    url: "https://mcp.amap.com/mcp?key=${AMAP_API_KEY}"
  

# Routing rules
routes:
  - hostname: "context7."
    upstream: "context7"
  - hostname: "amap."
    upstream: "amap"

# DIDAuth settings
didAuth:
  required: true