# MCP Server Proxy Configuration (Single Upstream)

# Server settings
port: 8088
endpoint: "/mcp"

# Single upstream MCP server (optional)
upstreamUrl: "https://mcp.amap.com/mcp?key=${AMAP_API_KEY}"

# Payment & chain configuration (optional)
serviceId: "mcp-proxy-service"
network: "test"
rpcUrl: "${ROOCH_RPC_URL}"
defaultAssetId: "0x3::gas_coin::RGas"
defaultPricePicoUSD: "1000000000000"
debug: false

# Custom tools registration
register:
  tools:
    - name: "echo.free"
      description: "Free echo service"
      pricePicoUSD: "0"
      parameters:
        type: "object"
        properties:
          text:
            type: "string"
    - name: "calc.add"
      description: "Add two numbers"
      pricePicoUSD: "0"
      parameters:
        type: "object"
        properties:
          a:
            type: "number"
          b:
            type: "number"