# MCP Server Proxy Configuration (Single Upstream)

# Server settings
port: 8088
endpoint: "/mcp"

# Single upstream MCP server (optional)
upstreamUrl: "https://mcp.amap.com/mcp?key=${AMAP_API_KEY}"

# Payment & chain configuration (optional)
serviceId: "mcp-proxy-service"
network: "test"
defaultPricePicoUSD: "1000000000"  # Default price for all tools (custom and upstream)
debug: true

# Custom tools registration (optional)
# register:
#   tools:
#     - name: "example.tool"
#       description: "Example custom tool"
#       pricePicoUSD: "1000000000000"  # 0.001 USD, if not specified, uses defaultPricePicoUSD
#       parameters:
#         type: "object"
#         properties:
#           input:
#             type: "string"
#     - name: "free.tool"
#       description: "Free tool example"
#       pricePicoUSD: "0"  # Free tool
#       parameters:
#         type: "object"