# Example billing configuration for the @nuwa-ai/payment-kit billing system
# This file demonstrates the YAML configuration format for different billing strategies

version: 1
serviceId: example-service
rules:
  # Rule for upload operations - higher cost due to processing requirements
  - id: upload-pricing
    when:
      path: "/upload"
      method: "POST"
    strategy:
      type: PerRequest
      price: "5000000000000000"  # 0.005 RAV units per upload

  # Rule for download operations - lower cost
  - id: download-pricing  
    when:
      path: "/download"
      method: "GET"
    strategy:
      type: PerRequest
      price: "1000000000000000"  # 0.001 RAV units per download

  # Rule for API calls - medium cost
  - id: api-call-pricing
    when:
      pathRegex: "^/api/"
    strategy:
      type: PerRequest
      price: "2000000000000000"  # 0.002 RAV units per API call

  # Default rule for all other operations
  - id: default-pricing
    default: true
    strategy:
      type: PerRequest
      price: "500000000000000"   # 0.0005 RAV units for other operations 