CREATE TABLE IF NOT EXISTS public.nowpayments_payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nowpayments_payment_id text UNIQUE NOT NULL,
  order_id text,
  amount_fiat numeric NOT NULL,
  currency_fiat text NOT NULL,
  status text NOT NULL,
  pay_currency text,
  payer_did text,
  transfer_tx text,
  ipn_payload jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  pay_address text,
  price_amount numeric,
  price_currency text,
  pay_amount numeric,
  order_description text,
  ipn_callback_url text,
  purchase_id text,
  amount_received numeric,
  payin_extra_id text,
  smart_contract text,
  network text,
  network_precision int,
  time_limit int,
  burning_percent numeric,
  expiration_estimate_date timestamptz,
  transferred_amount numeric DEFAULT 0,
  transferred_tx_hash text,
  network_fee numeric DEFAULT 0
);