providers = ["node"]

[phases.setup]
# Install Node.js and pnpm from Nix packages
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
# Install all dependencies
cmds = [
  "pnpm install"
]

[phases.build]
# Bundle TypeScript sources into dist/
cmds = [
  "pnpm run build"
]

[start]
# Start the gateway server, Railway will expose $PORT automatically
cmd = "pnpm start"
