name: Nuwa Packages Test

on:
  pull_request:
    paths:
      - 'nuwa-kit/typescript/packages/**'
      - '.github/workflows/packages-test.yml'
  push:
    branches:
      - main
    paths:
      - 'nuwa-kit/typescript/packages/**'
      - '.github/workflows/packages-test.yml'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            identity-kit: nuwa-kit/typescript/packages/identity-kit/**
            identity-kit-web: nuwa-kit/typescript/packages/identity-kit-web/**
            payment-kit: nuwa-kit/typescript/packages/payment-kit/**

  test:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.packages != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJSON(needs.detect-changes.outputs.packages) }}
        node-version: [20.x]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - name: Install dependencies
        run: |
          cd nuwa-kit/typescript
          pnpm install
      
      - name: Build dependencies
        run: |
          cd nuwa-kit/typescript
          # Build identity-kit first since other packages depend on it
          if [[ "${{ matrix.package }}" == "payment-kit" || "${{ matrix.package }}" == "identity-kit-web" ]]; then
            pnpm --filter @nuwa-ai/identity-kit build
          fi
      
      - name: Verify workspace setup
        run: |
          cd nuwa-kit/typescript
          # Ensure workspace dependencies are properly linked
          pnpm list --depth=0
      
      - name: Run tests for ${{ matrix.package }}
        env:
          NODE_OPTIONS: --experimental-global-webcrypto
        run: |
          PACKAGE_PATH=""
          if [[ "${{ matrix.package }}" == "identity-kit" ]]; then
            PACKAGE_PATH="nuwa-kit/typescript/packages/identity-kit"
          elif [[ "${{ matrix.package }}" == "identity-kit-web" ]]; then
            PACKAGE_PATH="nuwa-kit/typescript/packages/identity-kit-web"
          elif [[ "${{ matrix.package }}" == "payment-kit" ]]; then
            PACKAGE_PATH="nuwa-kit/typescript/packages/payment-kit"
          fi
          
          if [[ -n "$PACKAGE_PATH" ]]; then
            cd $PACKAGE_PATH
            # Ensure the built identity-kit is available for TypeScript resolution
            ls -la ../identity-kit/dist/ || echo "identity-kit dist not found"
            pnpm test
          fi 